### ISSUE TITLE
Config the closing of 'stale' issues

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/repo-mountie#18]
It'd be great to have a feature that allows for the automatic closing of an issue when found stale by the repo mountie. This could be done by applying some extra config within the rm-config file. Something like
```javascript
issues: { 
   autoClose: true,
   afterDays: 9, // number of days stale after last change to issue  
   closingComment: (daysStale) => `This issue was marked as stale after ${daysStale} days of inactivity. Please create a new issue if there is still a problem!`
}
```

**Comment by jleach** [comment]
When I add this feature I'm going to include `"applyLabel": "wontfix"` so it applies this label as it closes out the issue. If this is set to `null` it will keep existing labels. I was wondering if it should be able to skip issues if certain labels are applied or perhaps this just over complicates things.

Your thoughts?

**Comment by patricksimonian** [comment]
hmm good point. I think your idea on v1 is great. Were you thinking of a label called something like 'rm:ignore'?

Maybe in v2 the repo mount automatically creates this label for all gov repos and provides a description on how to use it? It seems like it would help alot. Taking a look at the Devhub's issues its rare that they are commented on so them automatically closing would be a bit annoying. 

Another thought is if `autoClose: false` it leaves the comment but does not close. That or there is an extra config for providing a warning. I see that alot in other peoples repos.
```js
warning: {
daysBeforeClose: 2,
message: (daysTillClose) => `message ...`
}

```

Sorry and last thing maybe this is auto closing business should only apply to non-teammembers/non-contributor created issues?
