### ISSUE TITLE
Improve command names

### ISSUE THREAD

**Issue by jleach** [bcgov/repo-mountie#43]
Consider improving the naming convention for commands so that it is more clear they are meant for the repo-mountie.

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/71202704-96727400-2251-11ea-84b4-de1252a40025.png)

repo-mountie too eager to help with issues that aren't related to it

**Comment by jleach** [comment]
@micheal-w-wells Fixed as part of #51 (currently in review).
